config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "", path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  
  has_many :technologies
  
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  
  validates_presence_of :title, :body, :main_image, :thumb_image

  # TODO Images
  # mount_uploader :thumb_image, PortfolioUploader
  # mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :destroy, :show]
  
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  layout 'portfolio'
  
  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    p "*" * 30
    p "params es igual a: #{params}"
    order = params[:order]
    order.each do |key, value|
      Portfolio.find_by_id(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end


  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy
    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      # TODO Images
                                      # :thumb_image,
                                      # :main_image,
                                      technologies_attributes: [:name]
                                     )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id]) 
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>

  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_area :subtitle, class: "form-control" %>
      </div>

      <% if false #TODO Images%>
      <div class="form-group">
        <%= f.file_field :main_image %>
      </div>
      

      <div class="form-group">
        <%= f.file_field :thumb_image %>
      </div>
      <% end %>
      

    </div>
    

    <div class="col-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>
  </div> 


  <hr>
  <div class="col-12">
    <h2>Techonologies Used</h2>
    <%= f.fields_for :technologies do |technology_form| %>
      <div class="form-group">
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name, class: "form-control" %>
      </div>
    <% end %>
     <div class="form-group">
      <%= f.submit "Save portfolio_item", class: "btn btn-primary" %>
    </div>
  </div>

 
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-portfolioid="<%=portfolio_item.id%>">
    <%= image_tag(portfolio_item.thumb_image) unless portfolio_item.thumb_image.nil? %>
    <div class="card-body">
      <p class="card-text"><span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %></p>
      <% if logged_in?(:site_admin) %>
	      <div class="d-flex justify-content-between align-items-center">
	        <div class="btn-group">
	          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit Item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %></button>
	          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Delete Portfolio Item', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></button>
	        </div>
	      </div>
	    <% end %>
    </div>
  </div>
</div>


<% if false %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag(portfolio_item.main_image) unless portfolio_item.main_image.nil? %></p>
  <p><%= image_tag(portfolio_item.thumb_image) unless portfolio_item.thumb_image.nil? %></p>
  <%= link_to "Edit Item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %> <!-- Se puede mandar portfolio_item.id -->
  <%= link_to 'Delete Portfolio Item', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } if
  logged_in?(:site_admin) %>


  <div class="card">
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <p class="card-text">
      
    </p>
  </div>

<% end %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |item| %>
	<p><%= link_to item.title, portfolio_path(item) %></p>
	<p><%= item.subtitle %></p>
	<p><%= item.body %></p>
	<p><%= image_tag(item.main_image) unless item.main_image.nil? %></p>
	<p><%= image_tag(item.thumb_image) unless item.thumb_image.nil? %></p>
	<%= link_to "Edit Item", edit_portfolio_path(item) if logged_in?(:site_admin) %> <!-- Se puede mandar item.id -->
	<%= link_to 'Delete Portfolio Item', item, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
	<h1>Edit Portfolio Item</h1>
	<!-- @portfolio debe estar disponible desde el controller para poder usarlo aquí. -->
	<%= render "form", portfolio_item: @portfolio_item %> <!-- #pasamos locals para la partial -->
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
			<%= render partial: 'portfolio_item', collection: @portfolio_items %>
		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
	<h1>Create a new Portfolio Item</h1>
	<!-- @portfolio debe estar disponible desde el controller para poder usarlo aquí. -->
	<%= render "form", portfolio_item: @portfolio_item %> <!-- #pasamos locals para la partial -->
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
	<div class= "row">
		<div class="col-md-7">
			<%= image_tag @portfolio_item.main_image, width: "100%" %>
		</div>

		<div class="col-md-5">
			<h1>	<%= @portfolio_item.title %> </h1>
			<hr>
			<em><%= @portfolio_item.subtitle %></em>
			<hr>
			<p><%= @portfolio_item.body %></p>
			<hr>


			<% if @portfolio_item.technologies.empty? == false %>
				<h3>Technologies Used:</h3>
				<% @portfolio_item.technologies.each do |technology| %>
					<p> <%= technology.name %> </p>
				<% end %>
			<% end %>
		</div>
	</div>
</div>