config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "", path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"><%= set_copyright %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<div class="inner">
  <h3 class="masthead-brand">Javier Ortiz Arellano</h3>
  <nav class="nav nav-masthead justify-content-center app-nav">
    <%= nav_helper 'nav-link', 'span' %>
		<%= login_helper("nav-link") %>
  </nav>
</div>

app/views/shared/_blog_footer.html.erb
<!-- start of footer -->
<footer class="blog-footer">
  <p><%= render "shared/application_footer" %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
<!-- end of footer -->

app/views/shared/_blog_masthead.html.erb
<!-- start of blog header -->
    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">Blog</h1>
        <p class="lead blog-description">AQUÍ ESCRIBO DE COSAS QUE ME INTERESAN.</p>
        <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
      </div>
    </div>
    <!-- end of blog header -->

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
 
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
	<div>
    <%= nav_helper '', 'div' %>
		<%= login_helper("nav-link") %>
	</div>
</div>

app/views/shared/_portfolio_footer.html.erb
<!-- start of footer -->
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "Ver todo el portafolio", portfolios_path %> / 
      <a href="#">Ir arriba</a>
    </p>
    <p><%= set_copyright %></p>
  </div>
</footer>
<!-- end of footer -->

app/views/shared/_portfolio_header.html.erb
<!-- start of masthead -->
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to "Visita mi Blog", blogs_path, class: "btn btn-primary my-2"%>
      <%= link_to "Acerca de mí", about_me_path, class: "btn btn-secondary my-2"%>
    </p>
  </div>
</section>
<!-- end of masthead -->

app/views/shared/_portfolio_nav.html.erb
<!-- start of navigation-->
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">Javier</h4>
        <p class="text-muted">Ingeniero Industrial, me gustan las matemáticas, la filosofía y la programación.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><div><%= login_helper("text-white") %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
      <strong>Javier</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>
<!-- end of navigation-->